server.port: 5001

spring:
  application:
    name: bot--telegram
  profiles:
    default: local

logging:
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss.SSS
  level:
    root: WARN
    org.zalando.logbook: TRACE
    br.com.fiap.SCJ.bottelegramspringboot: TRACE

bot:
  username: JarvisFIAP_bot
  token: ${BOT_TOKEN}

service:
  exchange:
    urlExchangeToday: https://economia.awesomeapi.com.br/json/last/{coinCodeFrom}-{coinCodeTo}
    defaultCoinCodeFrom: USD
    defaultCoinCodeTo: BRL

  weather:
    url: https://api.hgbrasil.com/weather?
    firstKey: key=a3299fbb
    secondKey: key=88615687
    fields_weather: '&fields=only_results,temp,date,condition_code,description,currently,city,humidity,sunrise,sunset,condition_slug,wind_speedy&city_name='
    fields_forecast: '&array_limit=7&fields=only_results,city,forecast,date,weekday,max,min,description,condition&city_name='

comandos:
  -
      nome: /hello
      descricao: eu te darei um alô
  -
      nome: /dolar
      descricao: cotação atual
  -
      nome: /clima <cidade>
      descricao: clima na cidade
  -
      nome: /previsao-tempo <cidade>
      descricao: previsão do tempo na cidade
  -
      nome: /calc <expressao>
      descricao: calcula expressão matemática
  -
      nome: /reverso <texto>
      descricao: inverte o texto
  -
      nome: /codificar <texto>
      descricao: codifica o texto
